#!/bin/bash

## === ZSH Addons === ##
git clone https://github.com/zsh-users/zsh-completions.git $XDG_STATE_HOME/zsh/zsh-completions
git clone https://github.com/zsh-users/zsh-autosuggestions.git $XDG_STATE_HOME/zsh/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $XDG_STATE_HOME/zsh/zsh-syntax-highlighting

## === ZSH Styles === ##
git clone https://github.com/seebi/dircolors-solarized.git $XDG_STATE_HOME/zsh/dircolors
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $XDG_STATE_HOME/zsh/powerlevel10k